from cepces import Base as CoreBase

NAME_EX: str
PRINCIPAL_EX: str

class Base(CoreBase):
    def __init__(self, handle) -> None: ...
    @property
    def handle(self): ...

class Context(Base):
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...

class PrincipalName(Base):
    def __init__(
        self, principal, name, context, host, service, service_type
    ) -> None: ...
    @property
    def primary(self): ...
    @property
    def instance(self): ...
    @property
    def realm(self): ...

class Principal(Base):
    def __init__(
        self, context, name=None, host=None, service=None, service_type=...
    ) -> None: ...
    def __del__(self) -> None: ...
    @property
    def primary(self): ...
    @property
    def instance(self): ...
    @property
    def realm(self): ...

def get_default_keytab_name() -> str: ...
