from cepces import Base as CoreBase
from typing import Any

NAME_EX: str
PRINCIPAL_EX: str

class Base(CoreBase):
    def __init__(self, handle: Any) -> None: ...
    @property
    def handle(self) -> Any: ...

class Context(Base):
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...

class PrincipalName(Base):
    def __init__(self, principal: Principal, name: str | None, context: Context, host: bytes | None, service: bytes | None, service_type: int) -> None: ...
    @property
    def primary(self) -> str: ...
    @property
    def instance(self) -> str | None: ...
    @property
    def realm(self) -> str: ...

class Principal(Base):
    def __init__(self, context: Context, name: str | None = None, host: bytes | None = None, service: bytes | None = None, service_type: int = ...) -> None: ...
    def __del__(self) -> None: ...
    @property
    def primary(self) -> str: ...
    @property
    def instance(self) -> str | None: ...
    @property
    def realm(self) -> str: ...

def get_default_keytab_name() -> str: ...
