import gssapi.raw.misc
from gssapi.raw.misc import GSSError as GSSError
from typing import ClassVar

__test__: dict

class BadChannelBindingsError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class BadMICError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class BadMechanismError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class BadNameError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class BadNameTypeError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class BadQoPError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class BadStatusError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class ContextReadError(ParameterReadError, MissingContextError): ...
class ContextWriteError(ParameterWriteError, MissingContextError): ...
class CredentialsReadError(ParameterReadError, MissingCredentialsError): ...
class CredentialsWriteError(ParameterWriteError, MissingCredentialsError): ...

class DuplicateCredentialsElementError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class DuplicateTokenError(SupplementaryError):
    SUPPLEMENTARY_CODE: ClassVar[int] = ...

class ExpiredContextError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class ExpiredCredentialsError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class ExpiredTokenError(SupplementaryError):
    SUPPLEMENTARY_CODE: ClassVar[int] = ...

class InvalidCredentialsError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class InvalidTokenError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class MalformedParameterError(gssapi.raw.misc.GSSError):
    CALLING_CODE: ClassVar[int] = ...

class MechanismNameRequiredError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class MissingContextError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class MissingCredentialsError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class NameReadError(ParameterReadError, BadNameError): ...
class NameTypeReadError(ParameterReadError, BadNameTypeError): ...

class OperationUnavailableError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...

class ParameterReadError(gssapi.raw.misc.GSSError):
    CALLING_CODE: ClassVar[int] = ...

class ParameterWriteError(gssapi.raw.misc.GSSError):
    CALLING_CODE: ClassVar[int] = ...

class SupplementaryError(gssapi.raw.misc.GSSError): ...
class TokenOutOfSequenceError(SupplementaryError): ...
class TokenReadError(ParameterReadError, InvalidTokenError): ...

class TokenTooEarlyError(TokenOutOfSequenceError):
    SUPPLEMENTARY_CODE: ClassVar[int] = ...

class TokenTooLateError(TokenOutOfSequenceError):
    SUPPLEMENTARY_CODE: ClassVar[int] = ...

class UnauthorizedError(gssapi.raw.misc.GSSError):
    ROUTINE_CODE: ClassVar[int] = ...
