import _cython_3_2_4limitednofinalize
import enum
import gssapi.raw.types as gssapi_types
from gssapi.raw._enum_extensions import ExtendableEnum as ExtendableEnum
from gssapi.raw.ext_dce_aead import unwrap_aead as unwrap_aead, wrap_aead as wrap_aead
from gssapi.raw.misc import GSSError as GSSError
from gssapi.raw.named_tuples import IOVUnwrapResult as IOVUnwrapResult
from typing import Callable, ClassVar

GSSAPI: str
__reduce_cython__: _cython_3_2_4limitednofinalize.cython_function_or_method
__setstate_cython__: _cython_3_2_4limitednofinalize.cython_function_or_method
__test__: dict
unwrap_iov: _cython_3_2_4limitednofinalize.cython_function_or_method
wrap_iov: _cython_3_2_4limitednofinalize.cython_function_or_method
wrap_iov_length: _cython_3_2_4limitednofinalize.cython_function_or_method

class IOV:
    AUTO_ALLOC_BUFFERS: ClassVar[set] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def count(self, *args, **kwargs): ...
    def index(self, *args, **kwargs): ...
    def __contains__(self, other) -> bool: ...
    def __getitem__(self, index): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __reduce__(self): ...
    def __reversed__(self): ...

class IOVBufferType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    data: ClassVar[IOVBufferType] = ...
    empty: ClassVar[IOVBufferType] = ...
    header: ClassVar[IOVBufferType] = ...
    mech_params: ClassVar[IOVBufferType] = ...
    mic_token: ClassVar[IOVBufferType] = ...
    padding: ClassVar[IOVBufferType] = ...
    sign_only: ClassVar[IOVBufferType] = ...
    stream: ClassVar[IOVBufferType] = ...
    trailer: ClassVar[IOVBufferType] = ...
    def __format__(self, *args, **kwargs) -> str: ...
