import _cython_3_2_4limitednofinalize
from gssapi.raw.misc import GSSError as GSSError
from gssapi.raw.named_tuples import AcquireCredResult as AcquireCredResult, AddCredResult as AddCredResult

GSSAPI: str
__test__: dict
acquire_cred_impersonate_name: _cython_3_2_4limitednofinalize.cython_function_or_method
add_cred_impersonate_name: _cython_3_2_4limitednofinalize.cython_function_or_method
