import _cython_3_2_4limitednofinalize
from gssapi.raw.types import MechType as MechType
from typing import ClassVar

GSSAPI: str
__test__: dict
indicate_mechs: _cython_3_2_4limitednofinalize.cython_function_or_method
inquire_mechs_for_name: _cython_3_2_4limitednofinalize.cython_function_or_method
inquire_names_for_mech: _cython_3_2_4limitednofinalize.cython_function_or_method

class GSSError(Exception):
    MESSAGE: ClassVar[str] = ...
    _parse_major_code: ClassVar[method] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def gen_message(self, *args, **kwargs): ...
    def get_all_statuses(self, *args, **kwargs): ...

class GSSErrorRegistry(type):
    _GSSErrorRegistry__registry: ClassVar[dict] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __call__(self, *args, **kwargs): ...
