import _cython_3_2_4limitednofinalize
from _typeshed import Incomplete
from typing import ClassVar

GSSAPI: str
__reduce_cython__: _cython_3_2_4limitednofinalize.cython_function_or_method
__setstate_cython__: _cython_3_2_4limitednofinalize.cython_function_or_method
__test__: dict

class OID:
    from_int_seq: ClassVar[method] = ...
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    dotted_form: Incomplete
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __reduce__(self): ...
