import _abc
import collections.abc
import enum
import gssapi.raw.oids
from gssapi.raw._enum_extensions import ExtendableEnum as ExtendableEnum
from typing import Callable, ClassVar

GSSAPI: str
__test__: dict

class AddressType(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    appletalk: ClassVar[AddressType] = ...
    arpanet: ClassVar[AddressType] = ...
    bisync: ClassVar[AddressType] = ...
    ccitt: ClassVar[AddressType] = ...
    chaos: ClassVar[AddressType] = ...
    datakit: ClassVar[AddressType] = ...
    decnet: ClassVar[AddressType] = ...
    dli: ClassVar[AddressType] = ...
    dss: ClassVar[AddressType] = ...
    ecma: ClassVar[AddressType] = ...
    hyperchannel: ClassVar[AddressType] = ...
    ibm_sna: ClassVar[AddressType] = ...
    ip: ClassVar[AddressType] = ...
    lat: ClassVar[AddressType] = ...
    local: ClassVar[AddressType] = ...
    nbs: ClassVar[AddressType] = ...
    null: ClassVar[AddressType] = ...
    osi_tp4: ClassVar[AddressType] = ...
    pup: ClassVar[AddressType] = ...
    x25: ClassVar[AddressType] = ...
    xerox_ns: ClassVar[AddressType] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class GenericFlagSet(collections.abc.MutableSet):
    MAX_VAL: ClassVar[int] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def add(self, *args, **kwargs): ...
    def discard(self, *args, **kwargs): ...
    def __and__(self, other): ...
    def __contains__(self, other) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __long__(self, *args, **kwargs): ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, other): ...
    def __rand__(self, other): ...
    def __ror__(self, other): ...
    def __rxor__(self, other): ...
    def __xor__(self, other): ...

class IntEnumFlagSet(GenericFlagSet):
    _abc_impl: ClassVar[_abc._abc_data] = ...
    _from_iterable: ClassVar[method] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __and__(self, other): ...
    def __iter__(self): ...
    def __or__(self, other): ...
    def __sub__(self, other): ...
    def __xor__(self, other): ...

class MechType:
    kerberos: ClassVar[gssapi.raw.oids.OID] = ...

class NameType:
    anonymous: ClassVar[gssapi.raw.oids.OID] = ...
    composite_export: ClassVar[gssapi.raw.oids.OID] = ...
    export: ClassVar[gssapi.raw.oids.OID] = ...
    hostbased_service: ClassVar[gssapi.raw.oids.OID] = ...
    kerberos_principal: ClassVar[gssapi.raw.oids.OID] = ...
    krb5_nt_principal_name: ClassVar[gssapi.raw.oids.OID] = ...
    machine_uid: ClassVar[gssapi.raw.oids.OID] = ...
    string_uid: ClassVar[gssapi.raw.oids.OID] = ...
    user: ClassVar[gssapi.raw.oids.OID] = ...

class RequirementFlag(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    anonymity: ClassVar[RequirementFlag] = ...
    channel_bound: ClassVar[RequirementFlag] = ...
    confidentiality: ClassVar[RequirementFlag] = ...
    dce_style: ClassVar[RequirementFlag] = ...
    delegate_to_peer: ClassVar[RequirementFlag] = ...
    extended_error: ClassVar[RequirementFlag] = ...
    identify: ClassVar[RequirementFlag] = ...
    integrity: ClassVar[RequirementFlag] = ...
    mutual_authentication: ClassVar[RequirementFlag] = ...
    ok_as_delegate: ClassVar[RequirementFlag] = ...
    out_of_sequence_detection: ClassVar[RequirementFlag] = ...
    protection_ready: ClassVar[RequirementFlag] = ...
    replay_detection: ClassVar[RequirementFlag] = ...
    transferable: ClassVar[RequirementFlag] = ...
    def __format__(self, *args, **kwargs) -> str: ...
